using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// Summary description for STD_MST_BAL
/// </summary>
public class CART_MST_BAL
{
    public string Order_No { get; set; }
    public int User_ID { get; set; }
    //public string User_Name { get; set; }
    //public string User_Pwd { get; set; }
    public int PID  { get; set; }
    public int PPR { get; set; }
    public int Quantity { get; set; } 
}